on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: streave/riscv-qemu:base
    steps:
      -name: Checkout the reposotory
      uses: actions/checkout@v3
      -run: cd helloworld && make
      -run: make cppcheck
      -run: cd ../gpio && make
      -run: make cppcheck