on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: streave/riscv-qemu:baseformat
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: cd helloworld && make cppcheck && make format && make 
      - run: cd gpio && make cppcheck && make format && make 
      - run: cd uled-driver && make cppcheck && make format && make 



